# Generated by Django 4.0.1 on 2022-01-12 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_commment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Commment',
            new_name='Comment',
        ),
    ]
